---
name: Feature Request
description: Suggest a new feature or improvement for the tutorial
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request

        Thank you for suggesting improvements to this tutorial! Your ideas help make it better for everyone.

  - type: textarea
    id: problem
    attributes:
      label: Problem/Current Situation
      description: What problem are you trying to solve? What's missing from the current tutorial?
      placeholder: |
        The tutorial currently [describe current state].
        This causes [describe the problem or limitation].
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see added or changed?
      placeholder: |
        I suggest adding [describe your proposed solution].
        This would include [list key elements or steps].
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - "New chapter/topic"
        - "Expand existing chapter"
        - "New script/tool"
        - "Configuration improvement"
        - "Documentation enhancement"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: |
        I also considered [alternative approach].
        But [why your preferred solution is better].
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information, examples, or context?
      placeholder: |
        This would be useful for [describe use case].
        Similar to how [reference other tutorials or tools].
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check all that apply
      options:
        - label: I have searched existing issues for similar requests
          required: true
        - label: This feature would benefit other users
        - label: I am willing to help implement this feature
        - label: I can provide examples or reference materials